name: WinsorCAM
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.2
  - torchvision=0.17
  - torchaudio=2.2
  - pytorch-cuda=12.1
  - numpy=1.26.*        # pin NumPy 1.x
  - matplotlib
  - imageio
  - ipykernel
  - ipywidgets
  - scikit-image
  - scikit-learn
  - tqdm
  - sympy
  - notebook
  - opencv              # install OpenCV from conda-forge (avoid opencv-python wheel)
  - pip
  - pip:
      - grad-cam
      - ttach